### ISSUE TITLE
Reserver resto Noel

### ISSUE THREAD

**Issue by philou-C** [deveaud-m/mariage#3]
1- offre
2- reserver

prio1
http://www.cromexquis.com
Regalade

prio2
http://www.zekitchengalerie.fr/kgb/

**Comment by deveaud-m** [comment]
T'as vu les offres du Crom'Exquis? Nettement plus professionnelles que la Régalade... 
On peut même aller directement en Métro depuis Vincennes jusqu'au Champs-Elysées et se faire prendre en photo dans les jolis jardins avant d'aller à pied au Crom'Exquis.

**Comment by deveaud-m** [comment]
Demande de devis envoyé à la Régalade!

**Comment by philou-C** [comment]
votre reservation pourra etre validee apres versement de 30% d accompte

**Comment by deveaud-m** [comment]
Acompte de 510€ enregistré sur le compte de Marion, il sera débité le 27 décembre.
E-Mail de confirmation envoyé à la régalade

**Comment by philou-C** [comment]
done- success
