### ISSUE TITLE
Préparer petits cadeaux souvenirs mariage civil

### ISSUE THREAD

**Issue by deveaud-m** [deveaud-m/mariage#5]
Colombe gravée en bois "Marion & Philippe - 27 décembre 2017"
Sachets d'épices aux petits mots érotiques: Élixir d'amour, poudre aphrodisiaque, senteurs enivrantes, extrait de désir... https://www.c-monetiquette.fr/etiquettes-autocollantes-objets.
Petite pochettes/boîtes personnalisées: https://selfpackaging.fr/

**Comment by philou-C** [comment]
done- success
